### ISSUE TITLE
AttributeError: module 'ssl' has no attribute 'wrap_socket'

### ISSUE THREAD

**Issue by FlorianFey** [teddziuba/django-sslserver#111]
Hi guys,

I get this error when I run the server with both if these commands:

```
python manage.py runsslserver  --certificate localhost.pem  --key localhost-key.pem   
python manage.py runsslserver
```

The certificate is available.  

`AttributeError: module 'ssl' has no attribute 'wrap_socket'`

I found a issue for this here that it should ne fixe, but it's still not working.

I am using Python 3.12.1.

Any solution for that?

Thx!
Flo

**Comment by ahmedsafadii** [comment]
for now you can do the following

python3.12/site-packages/sslserver/management/commands/runsslserver.py

replace

self.socket = ssl.wrap_socket(self.socket, certfile=certificate, ...)

with

context = ssl.SSLContext(ssl.PROTOCOL_TLS_SERVER)
context.load_cert_chain(certfile=certificate, keyfile=key)
self.socket = context.wrap_socket(self.socket, server_side=True)

**Comment by SergeoLacruz** [comment]
This is still needed and works on Ubuntu 24.04. Thanks for the hint.
